// <auto-generated />
namespace MvcRoomBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Removido_campo_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removido_campo_status));
        
        string IMigrationMetadata.Id
        {
            get { return "201502122349437_Removido_campo_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
